version: '2'
services:
  trainingsite-app:
    image: trainingsite
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://trainingsite-postgresql:5432/trainingsite
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8082:8082
  trainingsite-postgresql:
    extends:
      file: postgresql.yml
      service: trainingsite-postgresql
